title: "Zari Kanani"
description: "AI for Healthcare · Biomedical Engineering · Medical Device Regulation"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme


url: "https://zari-kanani.github.io"
baseurl: ""

author:
  name: "Zari Kanani"
  email: "zari.kanani.1991@gmail.com"
  linkedin: "https://www.linkedin.com/in/zarikanani"

# Add this line
include:
  - assets/css/style.css
defaults:
  - scope:
      path: ""
    values:
      layout: page
